# Generated by Django 5.0.14 on 2025-08-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointment", "0007_participant_cross_sys_uid_entranceguard"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="preview_weeks",
            field=models.IntegerField(default=4, verbose_name="可查看预约周数"),
        ),
    ]
