# Generated by Django 5.2.13 on 2026-04-16 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthboard', '0003_alter_birthboardrecord_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthboardRejectedIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasons', models.CharField(help_text='多选原因，逗号分隔', max_length=128)),
                ('detail', models.TextField(help_text='具体违规内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_issue', to='birthboard.birthboardrecord')),
            ],
        ),
    ]
