# Generated by Django 5.2.13 on 2026-04-17 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthboard', '0005_birthboardapprover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='birthboardrecord',
            name='first_approved',
            field=models.BooleanField(default=False, verbose_name='一审已通过'),
        ),
        migrations.AddField(
            model_name='birthboardrecord',
            name='first_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='一审时间'),
        ),
        migrations.AddField(
            model_name='birthboardrecord',
            name='first_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthboard_first_approved', to=settings.AUTH_USER_MODEL, verbose_name='一审人'),
        ),
        migrations.AddField(
            model_name='birthboardrecord',
            name='second_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='二审时间'),
        ),
        migrations.AddField(
            model_name='birthboardrecord',
            name='second_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthboard_second_approved', to=settings.AUTH_USER_MODEL, verbose_name='二审人'),
        ),
        migrations.CreateModel(
            name='BirthboardSecondApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', help_text='备注', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birthboard_second_approver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
