# Generated by Django 5.2.13 on 2026-04-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthboard', '0006_birthboardrecord_first_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthboardrecord',
            name='status',
            field=models.CharField(choices=[('waiting_confirm', '等待大家确认'), ('waiting_receiver', '等待寿星确认'), ('waiting_approve', '等待管理员审批'), ('ready', '等待投放'), ('ongoing', '投放进行中'), ('finished', '投放完成'), ('terminated', '已终止'), ('terminated_by_admin', '被管理员驳回'), ('canceled', '已撤销')], default='waiting_confirm', max_length=32, verbose_name='主流程状态'),
        ),
    ]
