# Generated by Django 5.2.13 on 2026-04-20 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthboard', '0007_alter_birthboardrecord_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('pay', '付款'), ('abort', '中止'), ('revoke', '撤销'), ('reject', '拒绝'), ('approve', '审核通过'), ('refund', '退款'), ('update', '更新')], max_length=16, verbose_name='操作类型')),
                ('before_status', models.CharField(blank=True, default='', max_length=32, verbose_name='修改前状态')),
                ('after_status', models.CharField(blank=True, default='', max_length=32, verbose_name='修改后状态')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='修改信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthboard_change_records', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_records', to='birthboard.birthboardrecord', verbose_name='投放记录')),
            ],
            options={
                'verbose_name': '投放变更记录',
                'verbose_name_plural': '投放变更记录',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
